apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- global/restricted-psp.yaml
- namespaces/routing-system/routing-system-ns.yaml
- namespaces/routing-system/traefik/overlays/cloud
- namespaces/sealed-secrets-system/sealed-secrets/overlays/cloud
- namespaces/sealed-secrets-system/sealed-secrets-system-ns.yaml
