apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

namespace: sealed-secrets-system

configMapGenerator:
- name: sealed-secrets-values
  files:
    - values.yaml=values/values.yaml

generatorOptions:
  disableNameSuffixHash: true