apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

namespace: routing-system

configMapGenerator:
- name: traefik-values
  files:
    - values.yaml=values/values.yaml

generatorOptions:
  disableNameSuffixHash: true