apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: sealed-secrets
  namespace: sealed-secrets-system
spec:
  url: https://bitnami-labs.github.io/sealed-secrets
  interval: 1m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: sealed-secrets-system
spec:
  interval: 1m
  chart:
    spec:
      chart: sealed-secrets
      version: 1.13.2-r2
      sourceRef:
        name: sealed-secrets
        kind: HelmRepository
        namespace: sealed-secrets-system
      interval: 1m
  valuesFrom:
  - kind: ConfigMap
    name: sealed-secrets-values
    valuesKey: values.yaml
